CREATE TABLE IF NOT EXISTS tbl_cotizacion (
    id_cotizacion BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre_completo VARCHAR(180) NOT NULL,
    correo VARCHAR(180) NOT NULL,
    telefono VARCHAR(30) NOT NULL,
    fechas_aproximadas VARCHAR(180) NOT NULL,
    fechas_seleccionadas TEXT NULL,
    cantidad_personas INT UNSIGNED NOT NULL,
    cantidad_dias INT UNSIGNED NULL,
    servicio_interes VARCHAR(180) NOT NULL,
    destino_detalles TEXT NOT NULL,
    estado_gestion ENUM('sin_abrir', 'abierto', 'gestionado') NOT NULL DEFAULT 'sin_abrir',
    estado_compra ENUM('pendiente', 'compro', 'no_compro') NOT NULL DEFAULT 'pendiente',
    presupuesto_viaje DECIMAL(12, 2) NULL,
    fechas_reales VARCHAR(180) NULL,
    paquete_comprado VARCHAR(180) NULL,
    destino_final VARCHAR(180) NULL,
    observaciones_internas TEXT NULL,
    source VARCHAR(50) NOT NULL DEFAULT 'web_form',
    opened_at DATETIME NULL,
    gestionado_at DATETIME NULL,
    compro_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_cotizacion),
    KEY idx_tbl_cotizacion_estado_gestion (estado_gestion),
    KEY idx_tbl_cotizacion_estado_compra (estado_compra),
    KEY idx_tbl_cotizacion_created_at (created_at),
    KEY idx_tbl_cotizacion_correo (correo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
